### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by valepu** [railt/parser#1]
Greetings,
I have discovered your library which seems to fit my needs and i was testing it. I have realized that the examples shown in the readme do not work and need some modifications. I have tested it with 1.2.0, 1.2.1 and dev-master versions.

In order to make the examples work i had to change all the names from int to strings, set the root to '0' and add "true" to the Terminals contructors (this to show the terminals in the XML when parsing a string) because the default for "kept" is false and they weren't showing in the parsed tree

```

	$lexer = (new Lexer())
	->add('T_WHITESPACE', '\\s+')
	->add('T_NUMBER', '\\d+')
	->add('T_PLUS', '\\+')
	->add('T_MINUS', '\\-')
	->skip('T_WHITESPACE'); 
	$grammar = new Grammar([
		new Concatenation('0', ['8', '6', '7'], 'expression'),  // expression = T_NUMBER operation ( ... )
		new Alternation('7', ['8', '0']),                     // ( T_NUMBER | expression )
		new Alternation('6', ['1', '2'], 'operation'),        // operation = T_PLUS | T_MINUS
		new Terminal('8', 'T_NUMBER', true),
		new Terminal('1', 'T_PLUS', true),
		new Terminal('2', 'T_MINUS', true),
	], '0');

	$parser = new Parser($lexer, $grammar);
	echo $parser->parse(File::fromSources('2 + 2 - 10 + 1000'));
```

I reckon this library is pretty new (just so you know: your first release was on my birthday this year!) so it might be normal that some things will change on the run. If this is intended I can make a PR to edit the readme

**Comment by SerafimArts** [comment]
@valepu Hello! Thanks for readme review.

Yes, сonstructor contains `false` by default and this is a documentation typo/mistake. I corrected it =)

P.S.
In general, I did not assume a manual way of constructing grammar and documentation is only needed to understand the principles of work. You can also use the grammar compiler to make it easier: https://github.com/railt/compiler
Thus, a [similar grammar](https://github.com/railt/compiler/blob/master/resources/grammar.pp2) can be assembled into a finished result in a fully automated way: https://github.com/railt/compiler/blob/master/src/Grammar/Parser.php

**Comment by valepu** [comment]
I was not aware about the compiler but since it was late when i tried the library i just wanted to see how it worked yesterday so i just copied the readme example.
Anyways, thanks a lot for the compiler, i'll be using it for sure! Last time i manually made a grammar (or an automata) I was still attending university :)
